version: '3.7'
networks:
    integration-tests:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.test
        depends_on: 
            - database
        environment: 
            - DB_HOST=database
            - DB_PORT=3306
        networks: 
            - integration-tests
        command: ["./waitMysql.sh", "database", "./tests.sh"]
    database:
        image: mysql:8.0
        volumes:
            - ./cmd/dbscheme:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: test
        networks: 
            - integration-tests