ARG GO_VERSION=1.13.4

FROM golang:${GO_VERSION}-alpine

RUN apk add --no-cache ca-certificates git
RUN apk add mysql mysql-client

WORKDIR /main

COPY go.mod go.sum ./

RUN go mod download

COPY cmd ./cmd
COPY tests.sh waitMysql.sh ./

RUN chmod +x waitMysql.sh
RUN chmod +x tests.sh